### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by philipsquire** [philipsquire/MI-449-js-serving-content-with-express#1]
## Make a fansite based on something you like (sandwiches, movies, emo bands, etc.)

@egillespie Can you take a look at this? It's [hosted here](https://philipsquire-js-serving-conten.herokuapp.com/) and meets the following criteria:

- [x] No code is repeated in your files; create a partial for any shared elements (`nav`, `head`, `header`, etc.)
- [x] Make a navigation to move throughout your site, using `forEach` to create a set of links to other data pages
- [x] Each item should have an object with an image, a link, a title, and more properties based on your topic (i.e. sandwich ingredients, movie release date, etc.)
- [x] Include at least 3 data pages and a homepage; routes should be created in Express for each
- [x] Use data appropriately with HTML tags (paragraphs in `p` tags, headings in `h1`-`h6`, etc.)
- [x] Use `express.static` to create a folder for static assets (images, stylesheets, etc.)
- [x] All pages on the hosted site are valid HTML (use the [W3C Validator](https://validator.w3.org/nu/?doc=) to verify each page)
- [x] Include a `.gitignore` file so that `node_modules` and any other unnecessary files are not commited to GitHub

I can't get two of the three images to render, and I don't know why. I still need to implement CSS, but everything else is complete.

**Comment by egillespie** [comment]
Hi Philip, this is looking pretty good! Don't worry about doing too much with the CSS, just show that you can load a CSS file from the public folder. 😉 

I'll offer a tip to help with the images along with some other feedback below. Can you touch these up?

### Fixing the images

**⚠️  Read my "Use on EJS page..." feedback before doing this to save some time**

It looks like the issue with the images is that they are using `source=` instead of `src=` as the attribute to set the image location.

In addition to fixing the image, would you mind running your hosted site's routes through the [W3C Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fphilipsquire-js-serving-conten.herokuapp.com%2Fbaccano) and fix the issues it reports? It's pointing out the `source` attribute issue along with some others.

### Use one EJS page template for all three content pages

Since your content pages are all practically identical, I recommend reusing a single EJS page template for all three routes. This will guarantee that your pages have the same structure and content while also reducing the amount of work required to fix validator issues.

Here's how I recommend going about this:

1. Rename `jojo.ejs` to `anime.ejs` and delete the other two anime EJS files

2. Replace `pages[1]` in `anime.ejs` with `data`

3. Update your `server.js` routes to use the new page and pass a new `data` parameter like this:
    ``` js
    app.get('/jojo', function (request, response) {
      response.render('pages/jojo', {
        pages: pages,
        data: pages[1]
      })
    })
    ```

Now the routes should use the same template and layout but show unique content. 🙂 

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🤘

**Comment by philipsquire** [comment]
I fixed everything!

**Comment by egillespie** [comment]
Excellent, your pages look great and I really like that refactor of the data pages. Nice job! 🥳  :shipit:
